version: '3.4'

# 宿主机sshd端口
x-publishedsshdport: &publishedsshdport
  "5822"

services: 
  ubuntu-cpp-env: 
    # 从docker hub 拉取
    image: lvhui/ubuntu-cpp-env
    # 从本地构建    
    # build: .
    container_name: ubuntu-cpp-env
    volumes: 
      - /etc/localtime:/etc/localtime:ro # 使docker中时区和宿主机一致
    ports: 
      - target: "22"
        published: *publishedsshdport
    cap_add: 
      - ALL
    restart: unless-stopped

