version: "3.7"

# 宿主机sshd端口
x-publishedsshdport: &publishedsshdport
  "5822"

# 宿主机jupyter端口
x-publishedjupyterport: &publishedjupyterport
  "5888"

services:
   
   aibase:
      # 从docker hub 拉取
      # image: lvhui/ubuntu-aibase
      # 从本地构建
      build: .
      container_name: aibase
      restart: unless-stopped
      ports: 
        - target: "22"
          published: *publishedsshdport
        - target: "8888"
          published: *publishedjupyterport
      restart: until-stopped
      volumes:
         - /etc/localtime:/etc/localtime:ro # 使docker中时区和宿主机一致
      cap_add:
         - ALL
      working_dir: /root
      entrypoint: jupyter lab
   